name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: whoan/docker-build-with-cache-action@v5
        name: Build docker image
        with:
          username: felipelincoln
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          image_name: graph-banking
          build_extra_args: "--build-arg MIX_ENV=dev --target build"
      
      - run: docker images
        
      - name: Start docker-compose services
        run: |
          docker-compose run --name test_container \
          -e MIX_ENV=test \
          -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
          -e GITHUB_SHA=$GITHUB_SHA \
          -e GITHUB_REF=$GITHUB_REF \
          -e GITHUB_EVENT_PATH=/home/runner/work/_temp/_github_workflow/event.json \
          -e GITHUB_EVENT_NAME=$GITHUB_EVENT_NAME \
          -d web /bin/sh
      - name: Copy github's event.json to container
        run: |
          docker exec test_container mkdir -p /home/runner/work/_temp/_github_workflow/
          docker cp $GITHUB_EVENT_PATH test_container:/home/runner/work/_temp/_github_workflow/
      
      - run: docker exec test_container ls -a
        
      - name: Run mix format
        run: docker exec test_container mix format --check-formatted --dry-run

      - name: Run mix credo
        run: docker exec test_container mix credo --strict
      
      - name: Run mix coveralls.post
        run: |
          docker exec -e MIX_ENV=test test_container mix coveralls.post --verbose --token "va3RJl4STxuXt32ffV6aCQDl4be2Tm0XC" --branch ${GITHUB_REF##*/} --name "GitHub Actions" --committer $GITHUB_ACTOR --message "${{ github.event.head_commit.message }}" --sha $GITHUB_SHA
             
             
             
             
             
             
             
             
             
             
             
             
