name: testing

on: [push, pull_request]

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - run: echo "${{ github.event.head_commit.message }}"
      
    - run: echo ${{ GITHUB_CONTEXT }}
